### ISSUE TITLE
Screen is frozen while Starting

### ISSUE THREAD

**Issue by Forstsam** [designer2k2/tbeam-lorawan-mapper#8]
I have the Problem that, when I start the device the screen is frozen by Lorawan Mapper 0.0.6 and nothing happens. Had somebody this problem too?

**Comment by designer2k2** [comment]
is there any serial output? 

if you keep it connected to platformio there should be some debug messages that help to see whats going on (or what is not)

**Comment by Forstsam** [comment]
There wasn't any serial output, but i went outside to try it with e frozenscreen and after a while it connected and the screen worked normal. So my problem was gone. Thanke you for your help!

**Comment by designer2k2** [comment]
ok thanks, seems that i waits for the first lora or gps
